name: no_sql_with_firebase
description: An app to demonstrate how to use a NoSQL database. Shown in a seminar in Database subject from Computer Science course.

publish_to: 'none'

version: 1.0.0+1

## Slidy Scripts 
vars:
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Modules, dependency injection and routing
  flutter_modular: ^2.0.1

  # State management  
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4

  # Functional programming
  dartz: any

  # Comparator
  equatable: any

  # Firebase
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  
  flutter:
    sdk: flutter

dev_dependencies:
  # Code generator for Modular bindings
  modular_codegen: any

  # Code generator for MobX Stores
  mobx_codegen: ^1.1.2

  # Generator
  build_runner: ^1.10.1

flutter:
  uses-material-design: true